hwj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('messages/', include('chat.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('open_requests', views.open_requests, name='open_requests'),
    path('create_request', views.create_request, name='create_request'),
    path('view_past_requests', views.past_requests, name='past_requests'),
    path('profile', views.profile, name='profile'),
    path('inbox', views.inbox, name='inbox'),
    path('non_profits', views.non_profits, name='non_profits'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
from django.utils import timezone
from PIL import Image


# Create your models here.


REQUEST_TYPES = [
    ('Furniture Service', 'Furniture Service'),
    ('Interpreter Service', 'Interpreter Service'),
    ('Transportation Service', 'Transportation Service'),
    ('Clothing Service', 'Clothing Service'),
    ('Food Service', 'Food Service'),
]

FEEDBACK_TYPES = [
    ('None', 'None'),
    ('Positive', 'Positive'),
    ('Negative', 'Negative'),
]


class Requests(models.Model):

    status = models.CharField(max_length=50, default="Incomplete")
    description = models.CharField(max_length=250)
    type = models.CharField(choices=REQUEST_TYPES, max_length=50, default='Item Service')
    date_created = models.DateTimeField(auto_now_add=True)
    date_appointment = models.DateTimeField(null=True)
    date_completed = models.DateTimeField(null=True)
    appointment_confirmed = models.BooleanField(default=False)
    appointment_suggested = models.BooleanField(default=False)
    requester = models.ForeignKey(User, on_delete=models.CASCADE)
    accepter = models.CharField(max_length=150, null=True)
    accepter_feedback = models.CharField(max_length=250, default='None')
    requester_feedback = models.CharField(max_length=250, default='None')
    reported = models.BooleanField(default=False)

    def __str__(self):
        return self.description


class RequestForm(ModelForm):

    class Meta:
        model = Requests
        fields = ['description', 'type']


class AcceptRequestForm(ModelForm):

    class Meta:
        model = Requests
        fields = ['accepter']


class CancelRequestForm(ModelForm):

    class Meta:
        model = Requests
        fields = ['accepter']


class DeleteRequestForm(ModelForm):

    class Meta:
        model = Requests
        fields = ['requester']


class CloseRequestForm(ModelForm):

    class Meta:
        model = Requests
        fields = ['status']


class ScheduleAppointmentForm(forms.Form):

    class Meta:
        model = Requests
        fields = ['date_appointment']
        widgets = {
            'date_appointment': forms.DateTimeInput(attrs={'class': 'datetime-input', 'format': '%Y-%m-%d %H:%M'})
        }


class ConfirmAppointmentForm(ModelForm):

    class Meta:
        model = Requests
        fields = ['appointment_confirmed']


class DateForm(forms.Form):

    date = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M', ''], required=False)


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default_profile_image.jpg", upload_to="profile_pics")
    created_count = models.IntegerField(default=0)
    accepted_count = models.IntegerField(default=0)
    deleted_count = models.IntegerField(default=0)
    completed_count = models.IntegerField(default=0)
    canceled_count = models.IntegerField(default=0)
    other_user_count = models.IntegerField(default=0)
    reported_count = models.IntegerField(default=0)
    user_anniversary = models.DateField(auto_now_add=True)
    is_moderator = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):

        super().save(*args, **kwargs)
        image = Image.open(self.image.path)

        if image.height > 500 or image.width > 500:

            output_size = (500, 500)
            image.thumbnail(output_size)
            image.save(self.image.path)

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserUpdateForm(forms.ModelForm):

    class Meta:

        model = User
        fields = ['username']


class ProfileUpdateForm(forms.ModelForm):

    class Meta:

        model = Profile
        fields = ['image']

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .models import Requests
from .models import RequestForm, AcceptRequestForm, CancelRequestForm, CloseRequestForm, DeleteRequestForm, \
    ScheduleAppointmentForm, DateForm, ConfirmAppointmentForm
from django.http import HttpResponseRedirect
from itertools import chain
from datetime import datetime
from django.utils import timezone
from chat.models import Thread
from django import forms
from .forms import ProfileUpdateForm, UserUpdateForm
from django.contrib.auth.models import User
import requests
import json
from django.http import HttpResponse

# Create your views here.


@login_required(login_url='/accounts/login/')
def index(request):

    user = request.user

    if request.method == "POST":

        primary_key = request.POST["primary_key"]
        primary_key = int(primary_key)
        current_request = Requests.objects.get(pk=primary_key)

        if 'cancel' in request.POST:
            current_request.date_appointment = None
            current_request.appointment_confirmed = False
            current_request.accepter = None
            current_request.status = "Incomplete"
            current_request.appointment_suggested = False
            current_request.save()
            user.profile.canceled_count += 1
            user.profile.save()

        if 'delete' in request.POST:
            current_request.delete()
            user.profile.deleted_count += 1
            user.profile.save()

        if 'report' in request.POST:
            current_request.reported = True
            current_request.save()
            user.profile.reported_count += 1
            user.profile.save()

        if 'message' in request.POST:

            if current_request.accepter == user.username:

                other_user = current_request.requester
                other_user = User.objects.get(username=other_user)

            else:

                other_user = current_request.accepter
                other_user = User.objects.get(username=other_user)

            potential_thread1 = Thread.objects.filter(first=user, second=other_user)
            potential_thread2 = Thread.objects.filter(first=other_user, second=user)

            if not potential_thread1 and not potential_thread2:

                new_thread = Thread(first=user, second=other_user)
                new_thread.save()

                return_url = '/messages/' + str(other_user)

                return HttpResponseRedirect(return_url)

            else:

                return_url = '/messages/' + str(other_user)

                return HttpResponseRedirect(return_url)

        if 'schedule' in request.POST:

            form = DateForm()

            if request.POST['new_date'] != '':
                new_date = request.POST['new_date']

                new_date = datetime.strptime(new_date, '%Y/%m/%d %H:%M').strftime('%Y-%m-%d %H:%M')
                # new_date = new_date[0:4] + "-" + new_date[5:7] + "-" + new_date[8:]
                current_request.date_appointment = new_date
                current_request.appointment_suggested = True
                current_request.status = "Appointment Not Yet Confirmed"
                current_request.save()

        if 'accept' in request.POST:

            current_request.appointment_confirmed = True
            current_request.status = "Confirmed"
            current_request.save()
            user.profile.accepted_count += 1
            user.profile.save()

        if 'reject' in request.POST:

            current_request.appointment_confirmed = False
            current_request.appointment_suggested = False
            current_request.date_appointment = None
            current_request.status = "Accepted"
            current_request.save()

        if 'cancel_appointment' in request.POST:

            current_request.appointment_confirmed = False
            current_request.date_appointment = None
            current_request.appointment_suggested = False
            current_request.status = "Accepted"
            current_request.save()

        if 'complete' in request.POST:

            current_request.status = "Complete"
            current_request.date_completed = datetime.now()
            current_request.save()
            user.profile.completed_count += 1
            user.profile.save()

        return HttpResponseRedirect('/')

    else:

        accepted_query_list = Requests.objects.exclude(status="Complete").exclude(reported=True).filter(accepter=user)
        created_query_list = Requests.objects.exclude(status="Complete").exclude(reported=True).filter(requester=user)

        form = DateForm()
        #schedule_context = {'form': form}

        return render(request, 'user/index.html',
                      {'accepted_requests': accepted_query_list, 'created_requests': created_query_list, 'form': form})


def register(request):

    if request.method == "POST":

        form = UserCreationForm(request.POST)

        if form.is_valid():

            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)

            return redirect('index')

    else:

        form = UserCreationForm()

    context = {'form': form}

    return render(request, 'registration/register.html', context)


def logout(request):

    logout(request)
    return redirect('/accounts/login')


def open_requests(request):

    if request.method == "GET":

        user = request.user

        context = Requests.objects.all().exclude(requester=user).filter(accepter=None)
        context = {'requests': context}

        #context = {'requests': Requests.objects.all().exclude(requester=user)}

        return render(request, 'user/open_requests.html', context)

    if request.method == "POST":

        form = AcceptRequestForm(request.POST)

        user = request.user
        primary_key = form.data["primary_key"]
        primary_key = int(primary_key)
        form.accepter = user

        current_request = Requests.objects.get(pk=primary_key)
        current_request.accepter = str(user)
        current_request.status = "Accepted"
        current_request.save()

        return HttpResponseRedirect('/')


def create_request(request):

    if request.method == "POST":

        form = RequestForm(request.POST)

        user = request.user

        if form.is_valid():

            type = form.cleaned_data['type']
            description = form.cleaned_data['description']
            current_request = form.save(commit=False)
            current_request.requester = user
            current_request.save()
            user.profile.created_count += 1
            user.profile.save()

            return HttpResponseRedirect('/')

    else:

        form = RequestForm()

    context = {'form': form}

    return render(request, 'user/create_request.html', context)


def past_requests(request):

    if request.method == "POST":

        if request.POST['button'] == "accepter_feedback":

            feedback = request.POST['feedback_response']

            primary_key = request.POST["primary_key"]
            primary_key = int(primary_key)

            current_request = Requests.objects.get(pk=primary_key)
            current_request.accepter_feedback = feedback
            current_request.save()

        if request.POST['button'] == "requester_feedback":

            feedback = request.POST['feedback_response']

            primary_key = request.POST["primary_key"]
            primary_key = int(primary_key)

            current_request = Requests.objects.get(pk=primary_key)
            current_request.requester_feedback = feedback
            current_request.save()

        return render(request, 'user/index.html')

    else:

        user = request.user

        past_accepter_query_list = Requests.objects.filter(requester=user, status="Complete")
        past_requester_query_list = Requests.objects.filter(accepter=user, status="Complete")

        #context = past_accepter_query_list | past_requester_query_list
        #context = {'requests': context}

        return render(request, 'user/past_requests.html', {'accepted_requests': past_accepter_query_list, 'created_requests': past_requester_query_list})


@login_required(login_url='/accounts/login/')
def profile(request):

    if request.method == "POST":

        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if profile_form.is_valid():
            profile_form.save()
            return render(request, 'user/profile.html')

    else:

        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }

    return render(request, 'user/profile.html', context)


def inbox(request):

    user = request.user

    message_thread_list_1 = Thread.objects.filter(first=user)
    message_thread_list_2 = Thread.objects.filter(second=user)

    message_list = message_thread_list_1 | message_thread_list_2

    return render(request, 'user/inbox.html', {'messages': message_list})


def non_profits(request):

    if request.method == "POST":

        charity_dict = {}
        city_input = request.POST["city_input"]
        state_input = request.POST["state_input"]

        json_response = get_nonprofits_from_zipcode(city_input, state_input)
        for item in json_response:
            name = item["charityName"]
            address = item["mailingAddress"]["streetAddress1"]
            city = item["mailingAddress"]["city"]
            zipcode = item["mailingAddress"]["postalCode"]

user/templates/user/base.html
<!doctype html>

<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Help Without Judgment</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Datepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous">
    <script type="text/javascript" src='http://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js'></script>
	<style>
		.container
		{
			font-family: 'Helvetica','Arial', sans-serif;
		}

		body
		{
			font-family: 'Helvetica','Arial', sans-serif;
		}

        #chat-items ul
		{
 			background-color: white;
    		max-height:120px;/*The important part*/
    		overflow:scroll;
    		-webkit-overflow-scrolling:touch;
 		}

        #chat-items li
		{
			list-style-type: none;
    	}

	</style>

    <script>
        $(function()
        {
            $("#id_date").datetimepicker();
            format: 'YYYY-MM-DD HH:MM'
        });
    </script>
</head>

<body style="background-color: #42A1C9;">

<!--Navbar Starts Here -->
	<nav class="mb-1 navbar navbar-expand-lg navbar-dark secondary-color lighten-1">
        <a class="navbar-brand" href="{% url 'index' %}">Help Without Judgment</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555" aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_request' %}">Create Request</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'open_requests' %}">Available Requests</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'past_requests' %}">Past Requests</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'inbox' %}">View Inbox</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'non_profits' %}">Local Non-Profits</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto nav-flex-icons">
                <li class="nav-item avatar dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-55" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="{{ user.profile.image.url }}" class="rounded-circle z-depth-0" alt="avatar image" width="100px" height="100px">
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg-right dropdown-secondary" aria-labelledby="navbarDropdownMenuLink-55">
                        <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <!--/.Navbar -->

	<!-- Dashboard (jumbotron) Begins -->
	<div style="background-color: #F9F8F8;" class="jumbotron d-flex align-items center min-vh-100" id="dashboard_greeting">
    	<!-- Dashboard greeting container Begins -->
		<div class="container text-center" id="jumbotron_text_container">
			<h1 class="display-4" align="center">{% block pageheader %}Dashboard{% endblock %}</h1>

            {% block greeting %}
            {% endblock greeting%}
            <hr class="my-4">

            {% block script %}
            {% endblock script%}

            {% block content %}
            {% endblock content%}

            {% block results %}
            {% endblock results %}

        </div><!-- End container -->
    </div> <!-- End jumbotron -->

    <!-- Footer Begins Here-->
    <footer class="page-footer font-small teal pt-4">

      <!-- Container Starts Here-->
      <div class="container-fluid text-center text-md-left">

        <!-- Grid Row Starts Here-->
        <div class="row">

          <!-- Grid Column Starts Here-->
          <div class="col-md-6 mt-md-0 mt-3">

            <!-- Content -->
            <h5 class="text-uppercase font-weight-bold">About</h5>
            <p>Help Without Judgment was conceived to make two things easier: providing direct help to local
                communities and receiving help without giving up your privacy. In this age of technology and
                connectivity, we hope you will find it in your heart to make a difference in the life
                of someone in your community.</p>

          </div> <!-- End of Grid Column -->

          <hr class="clearfix w-100 d-md-none pb-3">

          <!-- Grid Column Starts Here-->
          <div class="col-md-6 mb-md-0 mb-3">

            <!-- Content -->
            <h5 class="text-uppercase font-weight-bold">Advice</h5>
            <p>Although we are delighted that you are choosing to participate in this project, we want to remind you to
               never put yourself in a situation that makes you uncomfortable, and to meet in public places when possible.
               Your personal safety, the safety of your family, or anyone you care about is not worth being at risk. When
               in doubt, err on the side of caution or meet outside of a local police department to ensure your safety.</p>
          </div> <!-- End of Grid Column -->
        </div> <!-- End of Grid Row -->
      </div> <!-- End of Container -->

      <!-- Copyright Starts Here-->
      <div class="footer-copyright text-center py-3">© 2019 Copyright:
        <a href="https://helpwithoutjudgment.ga"> Help Without Judgment </a>
      </div> <!-- End of Copyright -->

    </footer> <!-- End of Footer -->
</body>
</html>

user/templates/user/create_request.html
{% extends "user/base.html" %}

{% block pageheader %}Create a New Service Request{% endblock %}

{% block content %}
    <div class="empty-form">
        <form action= "{% url 'create_request' %}" method="POST" class="form">

            {% csrf_token %}

            <div class="form-group">
                <label for="request_type">Request Type:</label>
                {{ form.type }}
            </div>

            <div class="form-group">
                <label for="request_description">Description:</label>
                {{ form.description }}
            </div>

            <button type="submit" class="btn btn-link" style="background: #40a9cf; color: #F9F8F8;">Submit</button>
        </form>
    </div>

{% endblock content %}

user/templates/user/inbox.html
{% extends "user/base.html" %}

{% block pageheader %}Inbox{% endblock pageheader %}

{% block content %}
    {% if messages.count > 0 %}
        <h4> These are your current conversations </h4>
        <hr class="my-4">
        <div class="row">
        {% for message in messages %}
            {% if message.first == user %}
                <div class="col-sm-4 col-md-r">
                    <div class="card" style="width: 18rem;">
                        <a id="message_url" href="/messages/{{ message.second.username }}"><img src="{{ message.second.profile.image.url }}" class="card-img-top" width="300px" height="250px" alt="profile_image"></a>
                        <div class="card-body">
                            <p class="card-text">Conversation with {{ message.second }}</p>
                            <p class="card-text">Last Message: {{ message.updated }}</p>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="col-sm-4 col-md-r">
                    <div class="card" style="width: 18rem;">
                        <a href="/messages/{{ message.first.username }}"><img src="{{ message.first.profile.image.url }}" class="card-img-top" width="300px" height="250px" alt="profile_image"></a>
                        <div class="card-body">
                            <p class="card-text">Conversation with {{ message.first }}</p>
                            <p class="card-text">Last Message: {{ message.updated }}</p>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        </div>
    {% else %}
        <h4> You do not currently have any conversations in your Inbox.</h4>
    {% endif %}
{% endblock content %}

user/templates/user/non_profits.html
{% extends "user/base.html" %}

{% block pageheader %}Local Non-Profit Organizations{% endblock pageheader %}

{% block content %}
    <h4>There are local resources that can provide different, and sometimes more long-term assistance.</h4>
    <hr class="my-4">
    <form action="{% url 'non_profits' %}" method="POST" class="empty-form">
        {% csrf_token %}
        <div class="form-group" align="center">
            <div class="col-sm-3 col-md-r">
                <div class="form-row">
                    <label for="city_lookup">Enter a city</label>
                    <input style="text-align:center;" name="city_input" type="text" id="city_input" class="form-control">
                    <label for="state_lookup"><br>Enter the state initials</label>
                    <input style="text-align:center;" name="state_input" type="text" id="state_input" class="form-control"><br>
                </div>
                <br><button type="submit" value="" name="submit" class="btn btn-link" style="background: #1a2a67; color: #F9F8F8;">Lookup Resources</button>
            </div>
        </div>
    </form>
{% endblock content %}

{% block results%}
    {% if charities %}
        <hr class="my-4">
        <div class="row">
        {% for item in charities.items %}
            <div class="col-sm-4 col-md-r">
                <div class="card">
                    <h5 class="card-header" style="background: #42A1C9; color: #F9F8F8;">{{ item.1.name }}</h5>
                    <div class="card-body" style="background: #795A63; color: #F9F8F8;">
                        <h5 class="card-text">Address: {{ item.1.address }}</h5>
                        <h5 class="card-text">City: {{ item.1.city }}</h5>
                        <h5 class="card-text">Zipcode: {{ item.1.zipcode }}</h5>
                        <h5 class="card-text">Website: {{ item.1.website }}</h5>
                    </div>
                </div><br>
            </div>
        {% endfor %}
        </div>
    {% endif %}
{% endblock results%}

user/templates/user/open_requests.html
{% extends "user/base.html" %}

{% block pageheader %}View Open Requests{% endblock %}

{% block content %}
    <div class="row">
        {% for request in requests %}
            <div class="col-sm-4 col-md-r">
                <div class="thumbnail">
                    {% if request.type == 'Furniture Service' %}
                    <img style="border: 2px solid black;" class="card-img" src="../static/registration/images/furniture_request_default_image.jpg" alt="furniture_request_default_image.jpg">
                    {% elif request.type == 'Food Service' %}
                    <img style="border: 2px solid black;" class="card-img" src="../static/registration/images/food_request_default_image.jpg" alt="food_request_default_image.jpg">
                    {% elif request.type == 'Clothing Service' %}
                    <img style="border: 2px solid black;" class="card-img" src="../static/registration/images/clothing_request_default_image.jpg" alt="clothing_request_default_image.jpg">
                    {% elif request.type == 'Interpreter Service' %}
                    <img style="border: 2px solid black;" class="card-img" src="../static/registration/images/interpreter_request_default_image.png" alt="interpreter_request_default_image.jpg">
                    {% elif request.type == 'Transportation Service' %}
                    <img style="border: 2px solid black;" class="card-img" src="../static/registration/images/transportation_request_default_image.jpg" alt="transportation_request_default_image.jpg">
                    {% endif %}
                    <div class="caption">
                        <h3><strong>Status: </strong>{{ request.status }}</h3>
                        <p><strong>Type: </strong>{{ request.type }}</p>
                        <p><strong>Requested By: </strong>{{ request.requester }}</p>
                        <p><strong>Description: </strong>{{ request.description }}</p>
                        <p><strong>Created On: </strong>{{ request.date_created|date:"F d, Y" }}</p>
                        {% if request.date_appointment != null and request.appointment_confirmed == False %}
                            <p><strong>Request Appointment: You have a pending schedule appointment.</strong></p>
                        {% elif request.date_appointment != null and request.appointment_confirmed == True %}
                            <p><strong>Request Appointment: </strong>{{ request.date_appointment }}</p>
                        {% endif %}
                        <p><strong>Completed On: </strong>{{ request.date_completed }}</p>
                        <div class="empty-form">
                            <form action= "{% url 'open_requests' %}" method="POST" class="form">
                                {% csrf_token %}
                                <input type="hidden" name="primary_key" value="{{ request.pk }}">
                                <button type="submit" class="btn btn-link" style="background: #48ad76; color: #F9F8F8;">Accept</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
{% endblock content %}